name: SAP CF APP 保活

on:
  schedule:
    # 每 20 分钟运行一次，以保持应用活跃
    - cron: "*/20 * * * *"
  # 当 docker-publish.yml 工作流成功完成时，也触发一次
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: keepalive
  cancel-in-progress: true

jobs:
  keepalive:
    # 仅当 workflow_run 事件是成功完成时才运行
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: KeepAlive via My Own Container
        # 使用我们自己构建和推送的镜像
        uses: docker://ghcr.io/${{ github.repository }}-keepalive:latest
        env:
          # --- 必须配置的 secrets ---
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_API: ${{ secrets.CF_API }}
          CF_ORG: ${{ secrets.CF_ORG }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
          CF_APP: ${{ secrets.CF_APP }}
